name: cat_breeds_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/cat.png"
  min_sdk_android: 21 # android min sdk min:16, default 21